server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://10.0.1.103:3306/wiseu_license?characterEncoding=utf8&autoReconnect=true
    username: wiseu_license
    password: wiseu_license
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace

